sudo: required
services:
  - docker

before_install:
  - docker build -t thomaseschneider/docker-react -f Dockerfile.dev .

script:
  - docker run thomaseschneider/docker-react npm run test -- --coverage
